const projects = [
  {
    "name": "2D Arcade Game",
    "original_name": "2DArcadeGame",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/2DArcadeGame",
    "description": "Space Invaders-style arcade game with game loop, player controls, and particle effects.",
    "features": ["🎮 Game Engine", "👾 Enemy Waves", "💥 Explosions"],
    "demo_url": "../C++/2DArcadeGame/demo.html"
  },
  {
    "name": "3D Graphics Engine",
    "original_name": "3dGraphicEngine",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/3dGraphicEngine",
    "description": "Interactive 3D renderer with rotation, shapes, and projection math.",
    "features": ["🎲 3D Shapes", "🔄 Rotation", "🖱️ Mouse Controls"],
    "demo_url": "../C++/3dGraphicEngine/demo.html"
  },
  {
    "name": "Chess Engine",
    "original_name": "ChessEngine",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/ChessEngine",
    "description": "Playable chess with piece movement, highlighting, and turn-based play.",
    "features": ["♔ Move Validation", "🎯 Move Highlights", "♟️ Full Board"],
    "demo_url": "../C++/ChessEngine/demo.html"
  },
  {
    "name": "Currency Converter",
    "original_name": "CurrencyConverter",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/CurrencyConverter",
    "description": "Convert between 5 currencies with live rates and swap functionality.",
    "features": ["💱 5 Currencies", "🔄 Swap Button", "📊 Rate Display"],
    "demo_url": "../C++/CurrencyConverter/demo.html"
  },
  {
    "name": "Data Analysis Tools",
    "original_name": "DataAnalysisTools",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/DataAnalysisTools",
    "description": "Statistical analysis with mean, median, standard deviation and charts.",
    "features": ["📊 Statistics", "📈 Bar Charts", "🔢 Sample Data"],
    "demo_url": "../C++/DataAnalysisTools/demo.html"
  },
  {
    "name": "File Encryption",
    "original_name": "FileEncryption",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/FileEncryption",
    "description": "Encrypt and decrypt text using Caesar, XOR, and Base64 algorithms.",
    "features": ["🔐 3 Algorithms", "🔒 Encrypt", "🔓 Decrypt"],
    "demo_url": "../C++/FileEncryption/demo.html"
  },
  {
    "name": "Game Server & Client",
    "original_name": "GameServerClient",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/GameServerClient",
    "description": "Simulated multiplayer server with client connections and packet stats.",
    "features": ["🖥️ Server Panel", "🎮 Client Connect", "📡 Live Stats"],
    "demo_url": "../C++/GameServerClient/demo.html"
  },
  {
    "name": "Neural Network",
    "original_name": "MachineLearningModel",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/MachineLearningModel",
    "description": "Visual neural network that trains to solve the XOR problem.",
    "features": ["🧠 Network Viz", "🚀 Training", "📊 Loss/Accuracy"],
    "demo_url": "../C++/MachineLearningModel/demo.html"
  },
  {
    "name": "Mad Libs Generator",
    "original_name": "MadLibsGenerator",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/MadLibsGenerator",
    "description": "Fun word game with multiple story templates and random words.",
    "features": ["📖 3 Stories", "🎲 Random Words", "✨ Highlights"],
    "demo_url": "../C++/MadLibsGenerator/demo.html"
  },
  {
    "name": "Number Guessing Game",
    "original_name": "NumberGuessingGame",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/NumberGuessingGame",
    "description": "Classic guessing game with hints and best score tracking.",
    "features": ["🎯 1-100 Range", "📈 Hints", "🏆 Best Score"],
    "demo_url": "../C++/NumberGuessingGame/demo.html"
  },
  {
    "name": "Ray Tracer",
    "original_name": "RayTracer",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/RayTracer",
    "description": "Real-time ray traced spheres with reflections, shadows, and animation.",
    "features": ["🌟 Ray Tracing", "🪞 Reflections", "🎬 Animation"],
    "demo_url": "../C++/RayTracer/demo.html"
  },
  {
    "name": "Rock Paper Scissors",
    "original_name": "RockPaperScissors",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/RockPaperScissors",
    "description": "Play against the computer with emoji visuals and score tracking.",
    "features": ["✊✋✌️ Classic Game", "📊 Score Tracking", "🎨 Visual UI"],
    "demo_url": "../C++/RockPaperScissors/demo.html"
  },
  {
    "name": "Music Player",
    "original_name": "SimpleMusicPlayer",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/SimpleMusicPlayer",
    "description": "Sleek music player with playlist, progress, and animated album art.",
    "features": ["🎵 Playlist", "⏯️ Controls", "🎨 Album Art"],
    "demo_url": "../C++/SimpleMusicPlayer/demo.html"
  },
  {
    "name": "Sudoku Solver",
    "original_name": "SudokuSolver",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/SudokuSolver",
    "description": "Solve puzzles using backtracking algorithm with visual feedback.",
    "features": ["🧩 Backtracking", "✨ Animation", "📝 Editable Grid"],
    "demo_url": "../C++/SudokuSolver/demo.html"
  },
  {
    "name": "Dragon's Lair Adventure",
    "original_name": "TextBasedAdventureGame",
    "category": "C++ Systems",
    "category_short": "C++",
    "path": "../C++/TextBasedAdventureGame",
    "description": "Branching story game with inventory, health, gold, and multiple endings.",
    "features": ["⚔️ Story Choices", "🎒 Inventory", "💀 Multiple Endings"],
    "demo_url": "../C++/TextBasedAdventureGame/demo.html"
  },
  {
    "name": "Blockchain Demo",
    "original_name": "BlockchainApplication",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/BlockchainApplication",
    "description": "Interactive blockchain demo with mining, proof-of-work, and block explorer.",
    "features": ["⛏️ Mine Blocks", "🔗 Block Explorer", "✓ Chain Validation"],
    "demo_url": "../Python/BlockchainApplication/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Scientific Calculator",
    "original_name": "Calculator",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Calculator",
    "description": "Modern scientific calculator with dark theme, history display, and advanced functions.",
    "features": ["🧮 Scientific Functions", "📜 History Display", "🎨 Dark Theme"],
    "demo_url": "../Python/Calculator/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "AI Chatbot",
    "original_name": "Chatbot",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Chatbot",
    "description": "Conversational chatbot with modern chat UI, message bubbles, and tech support mode.",
    "features": ["💬 Chat Bubbles", "🛠️ Support Mode", "⏰ Timestamps"],
    "demo_url": "../Python/Chatbot/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "ChatbotWhatsapp",
    "original_name": "ChatbotWhatsapp",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/ChatbotWhatsapp",
    "description": "WhatsApp integration chatbot using Twilio API.",
    "features": ["WhatsApp API", "Message Handling"],
    "demo_url": null,
    "run_command": null,
    "has_gui": false
  },
  {
    "name": "Clock & Timer Suite",
    "original_name": "Clock",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Clock",
    "description": "Modern clock with Pomodoro timer, stopwatch, and study session tracker.",
    "features": ["⏰ Digital Clock", "🍅 Pomodoro Timer", "📚 Study Mode"],
    "demo_url": "../Python/Clock/demo.html",
    "run_command": "python clock.py",
    "has_gui": true
  },
  {
    "name": "Currency Converter",
    "original_name": "CurrencyConverter",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/CurrencyConverter",
    "description": "Convert between 10+ currencies with live rates and swap functionality.",
    "features": ["💱 10 Currencies", "🔄 Quick Swap", "📊 Rate Display"],
    "demo_url": "../Python/CurrencyConverter/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "DataStreamingPipeline",
    "original_name": "DataStreamingPipeline",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/DataStreamingPipeline",
    "description": "Real-time data streaming and processing pipeline.",
    "features": ["Data Streams", "Pipeline Processing"],
    "demo_url": null,
    "run_command": null,
    "has_gui": false
  },
  {
    "name": "Data Visualization",
    "original_name": "DataVisulisationTool",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/DataVisulisationTool",
    "description": "Create beautiful charts from CSV data with bar, line, and pie chart options.",
    "features": ["📊 Multiple Chart Types", "📁 CSV Import", "🎨 Color Themes"],
    "demo_url": "../Python/DataVisulisationTool/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Image Resizer Pro",
    "original_name": "ImazeResizer",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/ImazeResizer",
    "description": "Resize images by pixels, percentage, or target file size with live preview.",
    "features": ["📷 Image Preview", "📐 Multiple Modes", "💾 Quality Control"],
    "demo_url": "../Python/ImazeResizer/demo.html",
    "run_command": "python ImageResizer.py",
    "has_gui": true
  },
  {
    "name": "ML House Predictor",
    "original_name": "MachineLearningModel",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/MachineLearningModel",
    "description": "Linear regression demo predicting house prices with training visualization.",
    "features": ["🤖 Train Model", "📈 R² Score", "🏠 Price Prediction"],
    "demo_url": "../Python/MachineLearningModel/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Mad Libs Generator",
    "original_name": "MadLibsGenerator",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/MadLibsGenerator",
    "description": "Fun word game with 5 story templates and dynamic input fields.",
    "features": ["📖 5 Stories", "🎲 Random Selection", "🎨 Fun Theme"],
    "demo_url": "../Python/MadLibsGenerator/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Number Guessing Game",
    "original_name": "NumberGuessingGame",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/NumberGuessingGame",
    "description": "Guess the number with difficulty levels, hints, and an AI solver demo.",
    "features": ["🎯 3 Difficulty Levels", "🤖 AI Binary Search", "📊 Progress Bar"],
    "demo_url": "../Python/NumberGuessingGame/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Object Detection",
    "original_name": "ObjectDetectionApp",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/ObjectDetectionApp",
    "description": "Object detection with simulation mode and optional OpenCV camera support.",
    "features": ["🎯 Live Detection", "📋 Detection Log", "📷 Camera Support"],
    "demo_url": "../Python/ObjectDetectionApp/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Password Manager",
    "original_name": "Pass",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Pass",
    "description": "Secure password manager with encryption, generator, and CSV storage.",
    "features": ["🔐 Encryption", "🎲 Password Generator", "📋 Copy to Clipboard"],
    "demo_url": "../Python/Pass/demo.html",
    "run_command": "python main.py",
    "has_gui": true
  },
  {
    "name": "QR Code Generator",
    "original_name": "QR_Codes",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/QR_Codes",
    "description": "Generate QR codes with custom colors and save as PNG.",
    "features": ["🎨 Custom Colors", "💾 Save PNG", "📱 Preview"],
    "demo_url": "../Python/QR_Codes/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Qr",
    "original_name": "Qr",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Qr",
    "description": "Advanced QR code generator with support for vCard, WiFi, and file encoding, plus integrated decoding.",
    "features": ["📶 WiFi Splitting", "📷 Decoder", "💾 High-Res Save"],
    "demo_url": null,
    "run_command": "python qrGen.py",
    "has_gui": true
  },
  {
    "name": "Build File Renamer",
    "original_name": "Renamer",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Renamer",
    "description": "Automatically rename build files with version, date, and project name.",
    "features": ["📁 Batch Rename", "📅 Date Stamps", "⚙️ Config File"],
    "demo_url": null,
    "run_command": "python build_renamer.py",
    "has_gui": false
  },
  {
    "name": "RestfulAPI",
    "original_name": "RestfulAPI",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/RestfulAPI",
    "description": "RESTful API implementation with Flask.",
    "features": ["REST Endpoints", "JSON Response"],
    "demo_url": null,
    "run_command": "python main.py",
    "has_gui": false
  },
  {
    "name": "SSC Math Prep",
    "original_name": "SSC",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/SSC",
    "description": "Math preparation tool with multiplication tables, squares, cubes, and roots.",
    "features": ["📊 Multiplication Tables", "🔢 Squares & Cubes", "📄 Export"],
    "demo_url": "../Python/SSC/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "SimpleWebApplication",
    "original_name": "SimpleWebApplication",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/SimpleWebApplication",
    "description": "Simple Flask web application.",
    "features": ["Flask", "Web Routes"],
    "demo_url": null,
    "run_command": "python app.py",
    "has_gui": false
  },
  {
    "name": "Cave Adventure",
    "original_name": "TextBasedAdventure",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/TextBasedAdventure",
    "description": "Interactive text adventure with graphical scene display, inventory, and action buttons.",
    "features": ["⚔️ Visual Scenes", "🎒 Inventory System", "🏆 Victory Path"],
    "demo_url": "../Python/TextBasedAdventure/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Tic-Tac-Toe AI",
    "original_name": "Tic-Tac-Toe",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/Tic-Tac-Toe",
    "description": "Play against an unbeatable AI using the Minimax algorithm.",
    "features": ["🤖 Minimax AI", "📊 Win Statistics", "🎯 Win Highlighting"],
    "demo_url": "../Python/Tic-Tac-Toe/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Weather App",
    "original_name": "WeatherApplication",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/WeatherApplication",
    "description": "Local weather display with IP-based geolocation and OpenWeatherMap API.",
    "features": ["🌡️ Temperature", "💧 Humidity", "📍 Auto-Location"],
    "demo_url": "../Python/WeatherApplication/demo.html",
    "run_command": "python Weatherapp.py",
    "has_gui": true
  },
  {
    "name": "Web Scraper",
    "original_name": "WebScrraper",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/WebScrraper",
    "description": "Extract links from websites with demo mode and CSV export.",
    "features": ["🔗 Link Extraction", "📄 CSV Export", "🧪 Demo Mode"],
    "demo_url": "../Python/WebScrraper/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "GitHub Avatar Downloader",
    "original_name": "githbProfile",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/githbProfile",
    "description": "Download GitHub profile pictures with user info display and avatar preview.",
    "features": ["👤 Avatar Preview", "📥 Download PNG", "ℹ️ User Info"],
    "demo_url": "../Python/githbProfile/demo.html",
    "run_command": "python gui_main.py",
    "has_gui": true
  },
  {
    "name": "Payment Analysis",
    "original_name": "payment",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../Python/payment",
    "description": "Comprehensive bank transaction analyzer with dashboard, categorization, and reporting.",
    "features": ["📊 Dashboard", "🏷️ Auto-Categorization", "📈 Visual Analytics"],
    "demo_url": null,
    "run_command": "python Payments.py",
    "has_gui": true
  },
  {
    "name": "DynamicWebsitewithBLog",
    "original_name": "DynamicWebsitewithBLog",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/DynamicWebsitewithBLog",
    "description": "Dynamic website with integrated blog functionality.",
    "features": ["Blog Posts", "Dynamic Content"],
    "demo_url": "../Web/DynamicWebsitewithBLog/index.html"
  },
  {
    "name": "E-commerce Platform",
    "original_name": "E-commercePlatform",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/E-commercePlatform",
    "description": "Full-featured e-commerce platform with shopping cart and checkout.",
    "features": ["🛒 Shopping Cart", "💳 Checkout", "📦 Products"],
    "demo_url": "../Web/E-commercePlatform/index.html"
  },
  {
    "name": "Interactive Data Viz",
    "original_name": "InteractiveDataVisualisation",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/InteractiveDataVisualisation",
    "description": "Interactive data visualization dashboard.",
    "features": ["📊 Charts", "🎛️ Interactive", "📈 Real-time"],
    "demo_url": "../Web/InteractiveDataVisualisation/index.html"
  },
  {
    "name": "Product Page",
    "original_name": "InteractiveProductPage",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/InteractiveProductPage",
    "description": "Interactive product showcase page.",
    "features": ["🖼️ Gallery", "🔍 Zoom", "📝 Details"],
    "demo_url": "../Web/InteractiveProductPage/index.html"
  },
  {
    "name": "Todo App",
    "original_name": "InteractiveTODO",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/InteractiveTODO",
    "description": "Interactive todo list with local storage.",
    "features": ["✅ Tasks", "💾 Persistence", "🎨 Modern UI"],
    "demo_url": "../Web/InteractiveTODO/index.html"
  },
  {
    "name": "ML Web App",
    "original_name": "MachineLearningPoweredWebApp",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/MachineLearningPoweredWebApp",
    "description": "Web application powered by machine learning.",
    "features": ["🤖 ML Model", "🌐 Web Interface"],
    "demo_url": "../Web/MachineLearningPoweredWebApp/index.html"
  },
  {
    "name": "Multiplayer Game",
    "original_name": "MultiplayerGame",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/MultiplayerGame",
    "description": "Browser-based multiplayer game.",
    "features": ["🎮 Multiplayer", "⚡ Real-time"],
    "demo_url": "../Web/MultiplayerGame/index.html"
  },
  {
    "name": "Payment Dashboard",
    "original_name": "PaymentDataAnalysis",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/PaymentDataAnalysis",
    "description": "Payment data analysis dashboard.",
    "features": ["📊 Analytics", "💰 Transactions"],
    "demo_url": "../Web/PaymentDataAnalysis/index.html"
  },
  {
    "name": "Progressive Web App",
    "original_name": "ProgressiveWebApp",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/ProgressiveWebApp",
    "description": "Installable Progressive Web App.",
    "features": ["📱 Installable", "🔄 Offline", "⚡ Fast"],
    "demo_url": "../Web/ProgressiveWebApp/index.html"
  },
  {
    "name": "Quiz Application",
    "original_name": "QuizApplication",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/QuizApplication",
    "description": "Interactive quiz with scoring system.",
    "features": ["❓ Questions", "📊 Scoring", "🎯 Timer"],
    "demo_url": "../Web/QuizApplication/index.html"
  },
  {
    "name": "Real-Time Dashboard",
    "original_name": "RealTimeDataDashboard",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/RealTimeDataDashboard",
    "description": "Real-time data dashboard with live updates.",
    "features": ["⚡ Live Updates", "📈 Charts", "🔔 Alerts"],
    "demo_url": "../Web/RealTimeDataDashboard/index.html"
  },
  {
    "name": "Single Page App",
    "original_name": "SinglePageApplication",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/SinglePageApplication",
    "description": "Modern single page application with routing.",
    "features": ["🔀 SPA Router", "🎨 Themes", "📱 Responsive"],
    "demo_url": "../Web/SinglePageApplication/index.html"
  },
  {
    "name": "Social Media Landing",
    "original_name": "SocialMediaLandingPage",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/SocialMediaLandingPage",
    "description": "Social media landing page design.",
    "features": ["🎨 Modern Design", "📱 Mobile First"],
    "demo_url": "../Web/SocialMediaLandingPage/index.html"
  },
  {
    "name": "Social Platform",
    "original_name": "SocialNetworkingPlatform",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/SocialNetworkingPlatform",
    "description": "Social networking platform features.",
    "features": ["👥 Profiles", "💬 Posts", "❤️ Interactions"],
    "demo_url": "../Web/SocialNetworkingPlatform/index.html"
  },
  {
    "name": "Static Website",
    "original_name": "StaticWebsite",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/StaticWebsite",
    "description": "Clean static website template.",
    "features": ["📄 HTML/CSS", "🎨 Responsive"],
    "demo_url": "../Web/StaticWebsite/index.html"
  },
  {
    "name": "Weather App (Web)",
    "original_name": "WeatherAPp",
    "category": "Web Development",
    "category_short": "Web",
    "path": "../Web/WeatherAPp",
    "description": "Web-based weather application.",
    "features": ["🌤️ Weather Data", "📍 Location", "🎨 UI"],
    "demo_url": "../Web/WeatherAPp/index.html"
  },
  {
    "name": "Internet Speed Meter",
    "original_name": "InternetSpeedMeter",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../InternetSpeedMeter",
    "description": "Modern, customizable Internet Speed Meter widget for Windows.",
    "features": ["📊 Real-time Monitor", "🎨 Modern UI", "📜 History Tracking"],
    "demo_url": null,
    "run_command": "python main.py",
    "has_gui": true
  },
  {
    "name": "Project Tracker Pro",
    "original_name": "ProjectTracker",
    "category": "Python Scripting",
    "category_short": "Python",
    "path": "../ProjectTracker",
    "description": "Comprehensive project management desktop app with analytics and time tracking.",
    "features": ["📊 Analytics Dashboard", "⏱️ Pomodoro Timer", "📋 Project Templates"],
    "demo_url": null,
    "run_command": "python project_tracker_enhanced.py",
    "has_gui": true
  }
];